name: Stream Processing Pipeline

on:
  push:
    paths:
      - 'data/**'  # Watches the "data" directory for new file commits
    branches:
      - main  # Trigger only on the main branch

jobs:
  notify-kafka:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Kafka CLI
        run: |
          wget https://archive.apache.org/dist/kafka/3.5.1/kafka_2.13-3.5.1.tgz
          tar -xvzf kafka_2.13-3.5.1.tgz
          mv kafka_2.13-3.5.1 /opt/kafka
          echo "export PATH=/opt/kafka/bin:$PATH" >> ~/.bashrc
          source ~/.bashrc

      - name: Send File Info to Kafka
        run: |
          FILE_PATH=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep '^data/')
          if [ -n "$FILE_PATH" ]; then
            echo "New file detected: $FILE_PATH"
            echo "{\"filename\": \"$FILE_PATH\", \"repo\": \"${{ github.repository }}\"}" | /opt/kafka/bin/kafka-console-producer.sh --broker-list ${{ secrets.KAFKA_BROKER }} --topic file-events
          fi
