name: Stream Processing Pipeline

on:
  push:
    paths:
      - 'data/**'
    branches:
      - main

jobs:
  notify-kafka:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Kafka CLI
        run: |
          wget https://archive.apache.org/dist/kafka/3.5.1/kafka_2.13-3.5.1.tgz
          tar -xvzf kafka_2.13-3.5.1.tgz
          mv kafka_2.13-3.5.1 /opt/kafka
          echo "export PATH=/opt/kafka/bin:$PATH" >> ~/.bashrc
          source ~/.bashrc

      - name: Debug File Detection
        run: |
          echo "GitHub SHA: ${{ github.sha }}"
          echo "Changed files:"
          git log -m -1 --name-only --pretty=format: ${{ github.sha }}
        

      - name: Send File Info to Kafka
        run: |
          FILE_PATH=$(git log -m -1 --name-only --pretty=format: ${{ github.sha }} | grep '^data/' || true)
          if [ ! -z "$FILE_PATH" ]; then
            echo "New file detected: $FILE_PATH"
            echo "{\"filename\": \"$FILE_PATH\", \"repo\": \"${{ github.repository }}\"}" | /opt/kafka/bin/kafka-console-producer.sh --broker-list ${{ secrets.KAFKA_BROKER }} --topic file-events
          else
            echo "No new files detected in the data/ directory."
          fi
        